### ISSUE TITLE
请教下，执行报错了

### ISSUE THREAD

**Issue by xiaoxiangjian** [zhaoqingpu/LangChainTest#1]
PS D:\langchainTest\LangChainTest-main> python .\main.py
Using embedded DuckDB with persistence: data will be stored in: ./db

请输入问题: 怎么增强体质
Traceback (most recent call last):
  File "D:\langchainTest\LangChainTest-main\main.py", line 46, in <module>
    res = qa(query)
  File "C:\Users\xx\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\chains\base.py", line 140, in __call__
    raise e
  File "C:\Users\xx\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\chains\base.py", line 134, in __call__

**Comment by baiwei0703** [comment]
应该是碰见同样错误了。楼上没写全。是ChatGLM.py 文件里，ChatGLM 的 _call  方法里面，response = requests.post("http://127.0.0.1:8000", headers=headers, json=data)  有一行这个导致的报错。但是我也没明白，为什么需要请求本地的8000端口。。。

**Comment by zhaoqingpu** [comment]
视频中提到了，我使用的是本地ChatGLM模型，启动了模型的Api接口，有条件建议直接使用openAI接口，不然的话只能自己部署ChatGLM 现在也有好多一键包，B站大神很多。

**Comment by zhaoqingpu** [comment]
> PS D:\langchainTest\LangChainTest-main> python .\main.py Using embedded DuckDB with persistence: data will be stored in: ./db
> 
> 请输入问题: 怎么增强体质 Traceback (most recent call last): File "D:\langchainTest\LangChainTest-main\main.py", line 46, in res = qa(query) File "C:\Users\xx\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\chains\base.py", line 140, in **call** raise e File "C:\Users\xx\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\chains\base.py", line 134, in **call**

视频中提到了，我使用的是本地ChatGLM模型，启动了模型的Api接口，有条件建议直接使用openAI接口，不然的话只能自己部署ChatGLM 现在也有好多一键包，B站大神很多。

**Comment by baiwei0703** [comment]
关于部署ChatGLM模型。可以借一下我从csdn上看到的这篇文章
原文： https://blog.csdn.net/zhaomengsen/article/details/130585397

**Comment by xiaoxiangjian** [comment]
close
